#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "commenting in Rive"
echo "Running formatting script..."

# Ensure using the correct Node.js version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 20 || exit 1

npx prettier --write .
echo "Staging changes..."
git add .
